language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.5
      sudo: required
      before_install:

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc g++; fi

script:
  - git clone https://github.com/SVF-tools/SVF.git
  - cd SVF
  - . ./build.sh
  - cd $TRAVIS_BUILD_DIR
  - ls
  - . ./gen_lib.sh
  - pwd
  - cd $TRAVIS_BUILD_DIR/SVF-npm
  - git push https://JasonZhongZexin:${git_key}@github.com/JasonZhongZexin/SVF-npm.git   HEAD:master

deploy:
  provider: releases
  skip_cleanup: true
  file: 
    - svflib_mac.tar.gz
    - svflib_ubuntu.tar.gz
  api_key: ${git_key}
  on:
    tags: true  