language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.5
      sudo: required
      before_install:

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc g++; fi

script:
  - git clone https://github.com/SVF-tools/SVF.git
  - cd SVF
  - . ./build.sh

before_deploy:
  - cd /home/travis/build/charles32110/autogen_svf_lib
  - . ./gen_lib.sh

deploy:
  provider: releases
  skip_cleanup: true
  file: "/home/travis/build/charles32110/autogen_svf_lib/autogen_svf_lib/*.tar.gz"
  api_key:
    secure: "$API_KEY"
  on:
    tags: true   
    draft: false 