language: generic

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
#      before_install:
#        - git clone https://github.com/charles32110/autogen_svf_lib.git
    - os: osx
      osx_image: xcode11.5
      sudo: required
#      before_install:
#        - git clone https://github.com/charles32110/autogen_svf_lib.git


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc g++; fi

script:
  - . ./gen_lib.sh